from django.db import models

from app import settings

from ratestask_region.models import Regions


class Ports(models.Model):
    """
    The Ports model corresponds to the Port entity and is constructed according to the port specifications described in
    the task. However, it is not applicable to this task since the table generated by Django using this model has a
    different name compared to the original database used in the task.
    """

    code = models.TextField(primary_key=True, default='', unique=True, blank=False, null=False,
                            max_length=settings.PORT_CODE_MAX_LENGTH)
    name = models.TextField(default='', blank=False, null=False, max_length=settings.PORT_NAME_MAX_LENGTH)
    parent_slug = models.ForeignKey(Regions, on_delete=models.SET_NULL, null=True, blank=True,
                                    related_name='port_region')

    class Meta:
        verbose_name = 'port'
        verbose_name_plural = 'ports'

    def __str__(self):
        return f'{self.code}'
